## 1.	Python Basics 

The Museum of Modern Art (MoMA) charges different admission prices depending on the visitor's age and student status. The admission prices are shown below.

Catergory and Admission Price: 
Adult (Age 17-64): USD 30;
Full-time Student: USD 17;
Senior (Age 65+): USD 22;
Age 16 or younger: Free.

1.1.	Define a Python function named ticket_price(age, is_student) that calculates and returns the admission price for one visitor based on the visitor's age and student status. (2 pts)

In [2]:
def ticket_price(age, is_student):
    if age <= 16:
        return 0
    elif is_student:
        return 17
    elif age >= 65:
        return 22
    elif 17 <= age <= 64:
        return 30
    else:
        return 0

1.2.	Using the function developed in Question 1.1, determine the admission price for each of the following visitors:

a.	A 25-year-old adult who is not a student. (0.5 pt)

b.	A 70-year-old senior who is not a student. (0.5 pt)

c.	An 18-year-old full-time student. (0.5 pt)


In [3]:
# a. A 25-year-old adult who is not a student
price_a = ticket_price(25, False)
print(f"a. 25-year-old non-student: ${price_a}")

# b. A 70-year-old senior who is not a student
price_b = ticket_price(70, False)
print(f"b. 70-year-old non-student: ${price_b}")

# c. An 18-year-old full-time student
price_c = ticket_price(18, True)
print(f"c. 18-year-old full-time student: ${price_c}")

a. 25-year-old non-student: $30
b. 70-year-old non-student: $22
c. 18-year-old full-time student: $17


1.3.	A family of three plans to visit MoMA. Their information is listed below:

Visitor 1: age 45, not a student

Visitor 2: age 40, not a student

Visitor 3: age 12, full-time student

Visitor 4: age 22, full-time student

Using the function developed in Question 1.1, calculate and report the total admission price for the family. (1.5 pts)

Hint: The function parameter “is_student” should take either True or False. For example, (age = 18, is_student = False) represents a person aged 18 but not in a student status.

In [4]:
# Store the visitor information (each item is a tuple: (age, is_student))
visitors = [
    (45, False),  # Visitor 1: age 45, not a student
    (40, False),  # Visitor 2: age 40, not a student
    (12, True),   # Visitor 3: age 12, full-time student
    (22, True)    # Visitor 4: age 22, full-time student
]

# Calculate the total admission price
total_price = sum(ticket_price(age, is_student) for age, is_student in visitors)

# Report the result
print(f"Total admission price: ${total_price}")

Total admission price: $77


# 2.NumPy 

Create a 10 x 10 matrix (2D-array) using the code below.

In [6]:
%pip install numpy
import numpy as np

np.random.seed(42)
A = np.random.randint(1, 101, size=(10, 10))

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ------------- -------------------------- 4.2/12.7 MB 33.9 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 48.9 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Please complete the following tasks:

2.1. Sort the values in each row of A in ascending order. Store the result in a new array named A_sorted and print the first three rows of A_sorted. (1 pt)

In [7]:
A_sorted = np.sort(A, axis=1)
print("First three rows of A_sorted:")
print(A_sorted[:3])

First three rows of A_sorted:
[[ 15  21  52  61  72  75  75  83  87  93]
 [  2   3  22  24  30  38  53  88  88 100]
 [  2  21  22  33  49  58  60  64  76  89]]


2.2. Reshape the original matrix A from a 10 × 10 array into a 20 × 5 array. Store the reshaped array in a variable named A_reshaped. Print the resulting matrix and its shape. (1 pt)

In [8]:
A_reshaped = A.reshape(20, 5)
print("\nA_reshaped:")
print(A_reshaped)
print("Shape of A_reshaped:", A_reshaped.shape)


A_reshaped:
[[ 52  93  15  72  61]
 [ 21  83  87  75  75]
 [ 88 100  24   3  22]
 [ 53   2  88  30  38]
 [  2  64  60  21  33]
 [ 76  58  22  89  49]
 [ 91  59  42  92  60]
 [ 80  15  62  62  47]
 [ 62  51  55  64   3]
 [ 51   7  21  73  39]
 [ 18   4  89  60  14]
 [  9  90  53   2  84]
 [ 92  60  71  44   8]
 [ 47  35  78  81  36]
 [ 50   4   2   6  54]
 [  4  54  93  63  18]
 [ 90  44  34  74  62]
 [100  14  95  48  15]
 [ 72  78  87  62  40]
 [ 85  80  82  53  24]]
Shape of A_reshaped: (20, 5)


2.3. Using array slicing, extract the elements located in rows 3 through 6 and columns 4 through 8 of A. Store the result in a new array and print it. (1 pt)

In [9]:
A_sliced = A[3:7, 4:9]
print("Extracted array: \n", A_sliced)

Extracted array: 
 [[60 80 15 62 62]
 [ 3 51  7 21 73]
 [14  9 90 53  2]
 [ 8 47 35 78 81]]


2.4. Split the original matrix A into two equal parts vertically, so that each resulting array contains 5 rows and 10 columns. Print the rank and size of each resulting array. (1 pt)

In [10]:
top_half, bottom_half = np.split(A, 2, axis=0)  # or np.vsplit(A, 2)

print("\nTop half rank (ndim):", top_half.ndim, "| size:", top_half.size)
print("Bottom half rank (ndim):", bottom_half.ndim, "| size:", bottom_half.size)


Top half rank (ndim): 2 | size: 50
Bottom half rank (ndim): 2 | size: 50


2.5. Using the two arrays obtained in Question 2.4, concatenate them side by side to create a new array with 5 rows and 20 columns. Print the resulting array and its shape. (1 pt)

In [11]:
A_concatenated = np.hstack((top_half, bottom_half))  # or np.concatenate((top_half, bottom_half), axis=1)

print("\nConcatenated array:")
print(A_concatenated)
print("Shape of concatenated array:", A_concatenated.shape)


Concatenated array:
[[ 52  93  15  72  61  21  83  87  75  75  18   4  89  60  14   9  90  53
    2  84]
 [ 88 100  24   3  22  53   2  88  30  38  92  60  71  44   8  47  35  78
   81  36]
 [  2  64  60  21  33  76  58  22  89  49  50   4   2   6  54   4  54  93
   63  18]
 [ 91  59  42  92  60  80  15  62  62  47  90  44  34  74  62 100  14  95
   48  15]
 [ 62  51  55  64   3  51   7  21  73  39  72  78  87  62  40  85  80  82
   53  24]]
Shape of concatenated array: (5, 20)
